class_name _EnumPlayerAnimations
extends EnumBase

###----------PROPERTIES----------###

const CLIMB_UP_LEDGE_LEFT:String = "climb_up_ledge_left"
const CLIMB_UP_LEDGE_RIGHT:String = "climb_up_ledge_right"
const DUCK_DO_BLOCK_LEFT:String = "duck_do_block_left"
const DUCK_DO_BLOCK_RIGHT:String = "duck_do_block_right"
const DUCK_DONE_BLOCK_LEFT:String = "duck_done_block_left"
const DUCK_DONE_BLOCK_RIGHT:String = "duck_done_block_right"
const DUCK_GO_BLOCK_LEFT:String = "duck_go_block_left"
const DUCK_GO_BLOCK_RIGHT:String = "duck_go_block_right"
const DUCK_LEFT:String = "duck_left"
const DUCK_RIGHT:String = "duck_right"
const DUCK_THROW_LEFT:String = "duck_throw_left"
const DUCK_THROW_RIGHT:String = "duck_throw_right"
const DUCK_WHIP_ATTACK_LEFT_1:String = "duck_whip_attack_left_1"
const DUCK_WHIP_ATTACK_LEFT_2:String = "duck_whip_attack_left_2"
const DUCK_WHIP_ATTACK_LEFT_3:String = "duck_whip_attack_left_3"
const DUCK_WHIP_ATTACK_RIGHT_1:String = "duck_whip_attack_right_1"
const DUCK_WHIP_ATTACK_RIGHT_2:String = "duck_whip_attack_right_2"
const DUCK_WHIP_ATTACK_RIGHT_3:String = "duck_whip_attack_right_3"
const FALL_DOWN_LEFT:String = "fall_down_left"
const FALL_DOWN_RIGHT:String = "fall_down_right"
const JUMP_UP_LEFT:String = "jump_up_left"
const JUMP_UP_RIGHT:String = "jump_up_right"
const ROLL_RIGHT:String = "roll_right"
const ROLL_LEFT:String = "roll_left"
const RUN_RIGHT:String = "run_right"
const RUN_LEFT:String = "run_left"
const RUN_TRANS_LEFT_TO_RIGHT:String = "run_trans_left_to_right"
const RUN_TRANS_RIGHT_TO_LEFT:String = "run_trans_right_to_left"
const STAND_DO_BLOCK_LEFT:String = "stand_do_block_left"
const STAND_DO_BLOCK_RIGHT:String = "stand_do_block_right"
const STAND_DONE_BLOCK_LEFT:String = "stand_done_block_left"
const STAND_DONE_BLOCK_RIGHT:String = "stand_done_block_right"
const STAND_GO_BLOCK_LEFT:String = "stand_go_block_left"
const STAND_GO_BLOCK_RIGHT:String = "stand_go_block_right"
const STAND_INJURED_LEFT:String = "stand_injured_left"
const STAND_INJURED_RIGHT:String = "stand_injured_right"
const STAND_LEFT:String = "stand_left"
const STAND_RIGHT:String = "stand_right"
const STAND_SWORD_ATTACK_LEFT_1:String = "stand_sword_attack_left_1"
const STAND_SWORD_ATTACK_LEFT_2:String = "stand_sword_attack_left_2"
const STAND_SWORD_ATTACK_LEFT_3:String = "stand_sword_attack_left_3"
const STAND_SWORD_ATTACK_RIGHT_1:String = "stand_sword_attack_right_1"
const STAND_SWORD_ATTACK_RIGHT_2:String = "stand_sword_attack_right_2"
const STAND_SWORD_ATTACK_RIGHT_3:String = "stand_sword_attack_right_3"
const STAND_THROW_LEFT:String = "stand_throw_left"
const STAND_THROW_RIGHT:String = "stand_throw_right"
const STAND_WHIP_ATTACK_LEFT_1:String = "stand_whip_attack_left_1"
const STAND_WHIP_ATTACK_LEFT_2:String = "stand_whip_attack_left_2"
const STAND_WHIP_ATTACK_LEFT_3:String = "stand_whip_attack_left_3"
const STAND_WHIP_ATTACK_RIGHT_1:String = "stand_whip_attack_right_1"
const STAND_WHIP_ATTACK_RIGHT_2:String = "stand_whip_attack_right_2"
const STAND_WHIP_ATTACK_RIGHT_3:String = "stand_whip_attack_right_3"
const TO_DUCK_LEFT:String = "to_duck_left"
const TO_DUCK_RIGHT:String = "to_duck_right"
const WALK_INJURED_LEFT:String = "walk_injured_left"
const WALK_INJURED_RIGHT:String = "walk_injured_right"

